-- CHECAR_ANUNCIO VERIFICA SE O ANUNCIO É DE UMA EMPRESA MATRIZ OU FILIAL E PRINTA O RESULTADO

CREATE OR REPLACE PROCEDURE CHECAR_ANUNCIO (ID_CHECK NUMBER) IS 
	TEST VARCHAR(4);
BEGIN

    SELECT CIPJMATRIZ
    INTO TEST
    FROM MARKETING
    WHERE CIPJMARK IN (
        SELECT CIPJMARK
        FROM ANUNCIO
        WHERE ID = ID_CHECK);
   
    IF TEST IS NULL THEN
        DBMS_OUTPUT.PUT_LINE('ANUNCIO DE EMPRESA MATRIZ');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ANUNCIO DE EMPRESA FILIAL');
    END IF;

END;







