-- ANUNCIO_DE_MATRIZ VERIFICA SE EXISTE ALGUMA EMPRESA MATRIZ (EMPRESA SEM MATRIZ ASSOCIADA A ELA) COM ANUNCIO DE ID IGUAL A ID_CHECK, PRINTANDO SE EXISTE OU NAO

CREATE OR REPLACE PROCEDURE ANUNCIO_DE_MATRIZ (ID_CHECK NUMBER) IS 
	TEST VARCHAR(4);
BEGIN

    SELECT COUNT(*)
    INTO TEST
    FROM MARKETING
    WHERE CIPJMARK IN (
        SELECT CIPJMARK
        FROM ANUNCIO
        WHERE ID = ID_CHECK)
    AND CIPJMATRIZ IS NULL;
   
    IF TEST = 0 THEN
        DBMS_OUTPUT.PUT_LINE('NENHUMA EMPRESA MATRIZ POSSUI ANUNCIO COM ID '||ID_CHECK);
    ELSE
        DBMS_OUTPUT.PUT_LINE('EXISTE EMPRESA MATRIZ COM ANUNCIO DE ID '||ID_CHECK);
    END IF;

END;

-- RANK_DA_TRANSP CLASSIFICA AS TRANSPORTADORAS EM BRONZE, SILVER OU GOLD DE ACORDO COM O NUMERO DE MOTORISTAS
-- GOLD TEM 10 OU MAIS, PRATA TEM ENTRE 5 E 10, BRONZE TEM MENOS DE 5
-- TAMBEM PRINTA O CIPJ (DADO NO ARGUMENTO) E O NUMERO DE MOTORISTAS

CREATE OR REPLACE PROCEDURE RANK_DA_TRANSP (CIPJ_TEST VARCHAR) IS
    NUM NUMBER;
BEGIN

    SELECT COUNT(*)
    INTO NUM
    FROM CAMINHAOMOTORISTA
    WHERE CIPJTRANS = CIPJ_TEST;

    IF NUM >= 10 THEN
        DBMS_OUTPUT.PUT_LINE('TRANSPORTADORA DE CIPJ '||CIPJ_TEST||' TEM '||NUM||' MOTORISTAS, SENDO UMA TRANSPORTADORA GOLD');
    ELSIF NUM >= 5 THEN
        DBMS_OUTPUT.PUT_LINE('TRANSPORTADORA DE CIPJ '||CIPJ_TEST||' TEM '||NUM||' MOTORISTAS, SENDO UMA TRANSPORTADORA SILVER');
    ELSE
        DBMS_OUTPUT.PUT_LINE('TRANSPORTADORA DE CIPJ '||CIPJ_TEST||' TEM '||NUM||' MOTORISTAS, SENDO UMA TRANSPORTADORA BRONZE');
    END IF;

END;

-- IS_LOJA_DE_PRIORIDADE DEFINE SE UMA LOJA EH DE PRIORIDADE OU NAO
-- UMA LOJA DE PRIORIDADE EH UMA LOJA QUE VENDEU PARA MAIS CLIENTES QUE A MEDIA DE CLIENTES ATENDIDOS DAS LOJAS

CREATE OR REPLACE PROCEDURE IS_LOJA_DE_PRIORIDADE (CIPJ_TEST VARCHAR) IS
    AVERAGE NUMBER;
    CLIENT NUMBER;
BEGIN

    SELECT AVG(QUANT)
    INTO AVERAGE
    FROM (
        SELECT COUNT(*) AS QUANT
        FROM COMPRA
        GROUP BY CIPJLOJA
    );

    SELECT COUNT(*)
    INTO CLIENT
    FROM COMPRA
    WHERE CIPJLOJA = CIPJ_TEST;


    IF CLIENT > AVERAGE THEN
        DBMS_OUTPUT.PUT_LINE('LOJA DE CIPJ '||CIPJ_TEST||' EH LOJA DE PRIORIDADE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('LOJA DE CIPJ '||CIPJ_TEST||' NAO EH LOJA DE PRIORIDADE');
    END IF;

END;






