-- ANUNCIO_DE_MATRIZ VERIFICA SE EXISTE ALGUMA EMPRESA MATRIZ (EMPRESA SEM MATRIZ ASSOCIADA A ELA) COM ANUNCIO DE ID IGUAL A ID_CHECK, PRINTANDO SE EXISTE OU NAO

CREATE OR REPLACE PROCEDURE ANUNCIO_DE_MATRIZ (ID_CHECK NUMBER) IS 
	TEST VARCHAR(4);
BEGIN

    SELECT COUNT(*)
    INTO TEST
    FROM MARKETING
    WHERE CIPJMARK IN (
        SELECT CIPJMARK
        FROM ANUNCIO
        WHERE ID = ID_CHECK)
    AND CIPJMATRIZ IS NULL;
   
    IF TEST = 0 THEN
        DBMS_OUTPUT.PUT_LINE('NENHUMA EMPRESA MATRIZ POSSUI ANUNCIO COM ID '||ID_CHECK);
    ELSE
        DBMS_OUTPUT.PUT_LINE('EXISTE EMPRESA MATRIZ COM ANUNCIO DE ID '||ID_CHECK);
    END IF;

END;







